// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestUser.proto

package com.chm.converter.test.protobuf;

public final class TestUserOuterClass {
    private TestUserOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TestUserOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tutorial.TestUser)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         *
         * @return Whether the user field is set.
         */
        boolean hasUser();

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         *
         * @return The user.
         */
        TestUser getUser();

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         */
        TestUserOrBuilder getUserOrBuilder();

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return Whether the userName field is set.
         */
        boolean hasUserName();

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return The userName.
         */
        String getUserName();

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return The bytes for userName.
         */
        com.google.protobuf.ByteString
        getUserNameBytes();

        /**
         * <code>optional string password = 3;</code>
         *
         * @return Whether the password field is set.
         */
        boolean hasPassword();

        /**
         * <code>optional string password = 3;</code>
         *
         * @return The password.
         */
        String getPassword();

        /**
         * <code>optional string password = 3;</code>
         *
         * @return The bytes for password.
         */
        com.google.protobuf.ByteString
        getPasswordBytes();

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return Whether the localDateTime field is set.
         */
        boolean hasLocalDateTime();

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return The localDateTime.
         */
        String getLocalDateTime();

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return The bytes for localDateTime.
         */
        com.google.protobuf.ByteString
        getLocalDateTimeBytes();

        /**
         * <code>optional string date = 5;</code>
         *
         * @return Whether the date field is set.
         */
        boolean hasDate();

        /**
         * <code>optional string date = 5;</code>
         *
         * @return The date.
         */
        String getDate();

        /**
         * <code>optional string date = 5;</code>
         *
         * @return The bytes for date.
         */
        com.google.protobuf.ByteString
        getDateBytes();

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return Whether the yearMonth field is set.
         */
        boolean hasYearMonth();

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return The yearMonth.
         */
        String getYearMonth();

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return The bytes for yearMonth.
         */
        com.google.protobuf.ByteString
        getYearMonthBytes();
    }

    /**
     * Protobuf type {@code tutorial.TestUser}
     */
    public static final class TestUser extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tutorial.TestUser)
            TestUserOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use TestUser.newBuilder() to construct.
        private TestUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TestUser() {
            userName_ = "";
            password_ = "";
            localDateTime_ = "";
            date_ = "";
            yearMonth_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new TestUser();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private TestUser(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            Builder subBuilder = null;
                            if (((bitField0_ & 0x00000001) != 0)) {
                                subBuilder = user_.toBuilder();
                            }
                            user_ = input.readMessage(TestUser.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(user_);
                                user_ = subBuilder.buildPartial();
                            }
                            bitField0_ |= 0x00000001;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            userName_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            password_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            localDateTime_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000010;
                            date_ = s;
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000020;
                            yearMonth_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestUserOuterClass.internal_static_tutorial_TestUser_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestUserOuterClass.internal_static_tutorial_TestUser_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestUser.class, Builder.class);
        }

        private int bitField0_;
        public static final int USER_FIELD_NUMBER = 1;
        private TestUser user_;

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         *
         * @return Whether the user field is set.
         */
        @Override
        public boolean hasUser() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         *
         * @return The user.
         */
        @Override
        public TestUser getUser() {
            return user_ == null ? TestUser.getDefaultInstance() : user_;
        }

        /**
         * <code>optional .tutorial.TestUser user = 1;</code>
         */
        @Override
        public TestUserOrBuilder getUserOrBuilder() {
            return user_ == null ? TestUser.getDefaultInstance() : user_;
        }

        public static final int USERNAME_FIELD_NUMBER = 2;
        private volatile Object userName_;

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return Whether the userName field is set.
         */
        @Override
        public boolean hasUserName() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return The userName.
         */
        @Override
        public String getUserName() {
            Object ref = userName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                userName_ = s;
                return s;
            }
        }

        /**
         * <code>optional string userName = 2;</code>
         *
         * @return The bytes for userName.
         */
        @Override
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PASSWORD_FIELD_NUMBER = 3;
        private volatile Object password_;

        /**
         * <code>optional string password = 3;</code>
         *
         * @return Whether the password field is set.
         */
        @Override
        public boolean hasPassword() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional string password = 3;</code>
         *
         * @return The password.
         */
        @Override
        public String getPassword() {
            Object ref = password_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                password_ = s;
                return s;
            }
        }

        /**
         * <code>optional string password = 3;</code>
         *
         * @return The bytes for password.
         */
        @Override
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LOCALDATETIME_FIELD_NUMBER = 4;
        private volatile Object localDateTime_;

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return Whether the localDateTime field is set.
         */
        @Override
        public boolean hasLocalDateTime() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return The localDateTime.
         */
        @Override
        public String getLocalDateTime() {
            Object ref = localDateTime_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                localDateTime_ = s;
                return s;
            }
        }

        /**
         * <code>optional string localDateTime = 4;</code>
         *
         * @return The bytes for localDateTime.
         */
        @Override
        public com.google.protobuf.ByteString
        getLocalDateTimeBytes() {
            Object ref = localDateTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                localDateTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATE_FIELD_NUMBER = 5;
        private volatile Object date_;

        /**
         * <code>optional string date = 5;</code>
         *
         * @return Whether the date field is set.
         */
        @Override
        public boolean hasDate() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <code>optional string date = 5;</code>
         *
         * @return The date.
         */
        @Override
        public String getDate() {
            Object ref = date_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                date_ = s;
                return s;
            }
        }

        /**
         * <code>optional string date = 5;</code>
         *
         * @return The bytes for date.
         */
        @Override
        public com.google.protobuf.ByteString
        getDateBytes() {
            Object ref = date_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                date_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int YEARMONTH_FIELD_NUMBER = 6;
        private volatile Object yearMonth_;

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return Whether the yearMonth field is set.
         */
        @Override
        public boolean hasYearMonth() {
            return ((bitField0_ & 0x00000020) != 0);
        }

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return The yearMonth.
         */
        @Override
        public String getYearMonth() {
            Object ref = yearMonth_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                yearMonth_ = s;
                return s;
            }
        }

        /**
         * <code>optional string yearMonth = 6;</code>
         *
         * @return The bytes for yearMonth.
         */
        @Override
        public com.google.protobuf.ByteString
        getYearMonthBytes() {
            Object ref = yearMonth_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                yearMonth_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(1, getUser());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, localDateTime_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, date_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, yearMonth_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getUser());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, localDateTime_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, date_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, yearMonth_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestUser)) {
                return super.equals(obj);
            }
            TestUser other = (TestUser) obj;

            if (hasUser() != other.hasUser()) return false;
            if (hasUser()) {
                if (!getUser()
                        .equals(other.getUser())) return false;
            }
            if (hasUserName() != other.hasUserName()) return false;
            if (hasUserName()) {
                if (!getUserName()
                        .equals(other.getUserName())) return false;
            }
            if (hasPassword() != other.hasPassword()) return false;
            if (hasPassword()) {
                if (!getPassword()
                        .equals(other.getPassword())) return false;
            }
            if (hasLocalDateTime() != other.hasLocalDateTime()) return false;
            if (hasLocalDateTime()) {
                if (!getLocalDateTime()
                        .equals(other.getLocalDateTime())) return false;
            }
            if (hasDate() != other.hasDate()) return false;
            if (hasDate()) {
                if (!getDate()
                        .equals(other.getDate())) return false;
            }
            if (hasYearMonth() != other.hasYearMonth()) return false;
            if (hasYearMonth()) {
                if (!getYearMonth()
                        .equals(other.getYearMonth())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUser()) {
                hash = (37 * hash) + USER_FIELD_NUMBER;
                hash = (53 * hash) + getUser().hashCode();
            }
            if (hasUserName()) {
                hash = (37 * hash) + USERNAME_FIELD_NUMBER;
                hash = (53 * hash) + getUserName().hashCode();
            }
            if (hasPassword()) {
                hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
                hash = (53 * hash) + getPassword().hashCode();
            }
            if (hasLocalDateTime()) {
                hash = (37 * hash) + LOCALDATETIME_FIELD_NUMBER;
                hash = (53 * hash) + getLocalDateTime().hashCode();
            }
            if (hasDate()) {
                hash = (37 * hash) + DATE_FIELD_NUMBER;
                hash = (53 * hash) + getDate().hashCode();
            }
            if (hasYearMonth()) {
                hash = (37 * hash) + YEARMONTH_FIELD_NUMBER;
                hash = (53 * hash) + getYearMonth().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestUser parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestUser parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestUser parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestUser parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestUser parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestUser parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestUser parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestUser parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestUser parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestUser parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestUser parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestUser parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestUser prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tutorial.TestUser}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tutorial.TestUser)
                TestUserOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestUserOuterClass.internal_static_tutorial_TestUser_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestUserOuterClass.internal_static_tutorial_TestUser_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestUser.class, Builder.class);
            }

            // Construct using com.chm.converter.test.protobuf.TestUserOuterClass.TestUser.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getUserFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                if (userBuilder_ == null) {
                    user_ = null;
                } else {
                    userBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                userName_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                password_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                localDateTime_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                date_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                yearMonth_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestUserOuterClass.internal_static_tutorial_TestUser_descriptor;
            }

            @Override
            public TestUser getDefaultInstanceForType() {
                return TestUser.getDefaultInstance();
            }

            @Override
            public TestUser build() {
                TestUser result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public TestUser buildPartial() {
                TestUser result = new TestUser(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    if (userBuilder_ == null) {
                        result.user_ = user_;
                    } else {
                        result.user_ = userBuilder_.build();
                    }
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.userName_ = userName_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.password_ = password_;
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.localDateTime_ = localDateTime_;
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.date_ = date_;
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.yearMonth_ = yearMonth_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestUser) {
                    return mergeFrom((TestUser) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestUser other) {
                if (other == TestUser.getDefaultInstance()) return this;
                if (other.hasUser()) {
                    mergeUser(other.getUser());
                }
                if (other.hasUserName()) {
                    bitField0_ |= 0x00000002;
                    userName_ = other.userName_;
                    onChanged();
                }
                if (other.hasPassword()) {
                    bitField0_ |= 0x00000004;
                    password_ = other.password_;
                    onChanged();
                }
                if (other.hasLocalDateTime()) {
                    bitField0_ |= 0x00000008;
                    localDateTime_ = other.localDateTime_;
                    onChanged();
                }
                if (other.hasDate()) {
                    bitField0_ |= 0x00000010;
                    date_ = other.date_;
                    onChanged();
                }
                if (other.hasYearMonth()) {
                    bitField0_ |= 0x00000020;
                    yearMonth_ = other.yearMonth_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestUser parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestUser) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private TestUser user_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    TestUser, Builder, TestUserOrBuilder> userBuilder_;

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             *
             * @return Whether the user field is set.
             */
            public boolean hasUser() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             *
             * @return The user.
             */
            public TestUser getUser() {
                if (userBuilder_ == null) {
                    return user_ == null ? TestUser.getDefaultInstance() : user_;
                } else {
                    return userBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public Builder setUser(TestUser value) {
                if (userBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    user_ = value;
                    onChanged();
                } else {
                    userBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public Builder setUser(
                    Builder builderForValue) {
                if (userBuilder_ == null) {
                    user_ = builderForValue.build();
                    onChanged();
                } else {
                    userBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public Builder mergeUser(TestUser value) {
                if (userBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0) &&
                            user_ != null &&
                            user_ != TestUser.getDefaultInstance()) {
                        user_ =
                                TestUser.newBuilder(user_).mergeFrom(value).buildPartial();
                    } else {
                        user_ = value;
                    }
                    onChanged();
                } else {
                    userBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public Builder clearUser() {
                if (userBuilder_ == null) {
                    user_ = null;
                    onChanged();
                } else {
                    userBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public Builder getUserBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getUserFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            public TestUserOrBuilder getUserOrBuilder() {
                if (userBuilder_ != null) {
                    return userBuilder_.getMessageOrBuilder();
                } else {
                    return user_ == null ?
                            TestUser.getDefaultInstance() : user_;
                }
            }

            /**
             * <code>optional .tutorial.TestUser user = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    TestUser, Builder, TestUserOrBuilder>
            getUserFieldBuilder() {
                if (userBuilder_ == null) {
                    userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            TestUser, Builder, TestUserOrBuilder>(
                            getUser(),
                            getParentForChildren(),
                            isClean());
                    user_ = null;
                }
                return userBuilder_;
            }

            private Object userName_ = "";

            /**
             * <code>optional string userName = 2;</code>
             *
             * @return Whether the userName field is set.
             */
            public boolean hasUserName() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional string userName = 2;</code>
             *
             * @return The userName.
             */
            public String getUserName() {
                Object ref = userName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    userName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string userName = 2;</code>
             *
             * @return The bytes for userName.
             */
            public com.google.protobuf.ByteString
            getUserNameBytes() {
                Object ref = userName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string userName = 2;</code>
             *
             * @param value The userName to set.
             * @return This builder for chaining.
             */
            public Builder setUserName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string userName = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string userName = 2;</code>
             *
             * @param value The bytes for userName to set.
             * @return This builder for chaining.
             */
            public Builder setUserNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                bitField0_ |= 0x00000002;
                userName_ = value;
                onChanged();
                return this;
            }

            private Object password_ = "";

            /**
             * <code>optional string password = 3;</code>
             *
             * @return Whether the password field is set.
             */
            public boolean hasPassword() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional string password = 3;</code>
             *
             * @return The password.
             */
            public String getPassword() {
                Object ref = password_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string password = 3;</code>
             *
             * @return The bytes for password.
             */
            public com.google.protobuf.ByteString
            getPasswordBytes() {
                Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string password = 3;</code>
             *
             * @param value The password to set.
             * @return This builder for chaining.
             */
            public Builder setPassword(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string password = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPassword() {
                bitField0_ = (bitField0_ & ~0x00000004);
                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            /**
             * <code>optional string password = 3;</code>
             *
             * @param value The bytes for password to set.
             * @return This builder for chaining.
             */
            public Builder setPasswordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                bitField0_ |= 0x00000004;
                password_ = value;
                onChanged();
                return this;
            }

            private Object localDateTime_ = "";

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @return Whether the localDateTime field is set.
             */
            public boolean hasLocalDateTime() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @return The localDateTime.
             */
            public String getLocalDateTime() {
                Object ref = localDateTime_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    localDateTime_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @return The bytes for localDateTime.
             */
            public com.google.protobuf.ByteString
            getLocalDateTimeBytes() {
                Object ref = localDateTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    localDateTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @param value The localDateTime to set.
             * @return This builder for chaining.
             */
            public Builder setLocalDateTime(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                localDateTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLocalDateTime() {
                bitField0_ = (bitField0_ & ~0x00000008);
                localDateTime_ = getDefaultInstance().getLocalDateTime();
                onChanged();
                return this;
            }

            /**
             * <code>optional string localDateTime = 4;</code>
             *
             * @param value The bytes for localDateTime to set.
             * @return This builder for chaining.
             */
            public Builder setLocalDateTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                bitField0_ |= 0x00000008;
                localDateTime_ = value;
                onChanged();
                return this;
            }

            private Object date_ = "";

            /**
             * <code>optional string date = 5;</code>
             *
             * @return Whether the date field is set.
             */
            public boolean hasDate() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>optional string date = 5;</code>
             *
             * @return The date.
             */
            public String getDate() {
                Object ref = date_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    date_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string date = 5;</code>
             *
             * @return The bytes for date.
             */
            public com.google.protobuf.ByteString
            getDateBytes() {
                Object ref = date_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    date_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string date = 5;</code>
             *
             * @param value The date to set.
             * @return This builder for chaining.
             */
            public Builder setDate(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                date_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string date = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDate() {
                bitField0_ = (bitField0_ & ~0x00000010);
                date_ = getDefaultInstance().getDate();
                onChanged();
                return this;
            }

            /**
             * <code>optional string date = 5;</code>
             *
             * @param value The bytes for date to set.
             * @return This builder for chaining.
             */
            public Builder setDateBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                bitField0_ |= 0x00000010;
                date_ = value;
                onChanged();
                return this;
            }

            private Object yearMonth_ = "";

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @return Whether the yearMonth field is set.
             */
            public boolean hasYearMonth() {
                return ((bitField0_ & 0x00000020) != 0);
            }

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @return The yearMonth.
             */
            public String getYearMonth() {
                Object ref = yearMonth_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    yearMonth_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @return The bytes for yearMonth.
             */
            public com.google.protobuf.ByteString
            getYearMonthBytes() {
                Object ref = yearMonth_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    yearMonth_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @param value The yearMonth to set.
             * @return This builder for chaining.
             */
            public Builder setYearMonth(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                yearMonth_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearYearMonth() {
                bitField0_ = (bitField0_ & ~0x00000020);
                yearMonth_ = getDefaultInstance().getYearMonth();
                onChanged();
                return this;
            }

            /**
             * <code>optional string yearMonth = 6;</code>
             *
             * @param value The bytes for yearMonth to set.
             * @return This builder for chaining.
             */
            public Builder setYearMonthBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                bitField0_ |= 0x00000020;
                yearMonth_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:tutorial.TestUser)
        }

        // @@protoc_insertion_point(class_scope:tutorial.TestUser)
        private static final TestUser DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestUser();
        }

        public static TestUser getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TestUser>
                PARSER = new com.google.protobuf.AbstractParser<TestUser>() {
            @Override
            public TestUser parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TestUser(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TestUser> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TestUser> getParserForType() {
            return PARSER;
        }

        @Override
        public TestUser getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tutorial_TestUser_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tutorial_TestUser_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016TestUser.proto\022\010tutorial\"\362\001\n\010TestUser\022" +
                        "%\n\004user\030\001 \001(\0132\022.tutorial.TestUserH\000\210\001\001\022\025" +
                        "\n\010userName\030\002 \001(\tH\001\210\001\001\022\025\n\010password\030\003 \001(\tH" +
                        "\002\210\001\001\022\032\n\rlocalDateTime\030\004 \001(\tH\003\210\001\001\022\021\n\004date" +
                        "\030\005 \001(\tH\004\210\001\001\022\026\n\tyearMonth\030\006 \001(\tH\005\210\001\001B\007\n\005_" +
                        "userB\013\n\t_userNameB\013\n\t_passwordB\020\n\016_local" +
                        "DateTimeB\007\n\005_dateB\014\n\n_yearMonthB!\n\037com.c" +
                        "hm.converter.test.protobufb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_tutorial_TestUser_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tutorial_TestUser_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tutorial_TestUser_descriptor,
                new String[]{"User", "UserName", "Password", "LocalDateTime", "Date", "YearMonth", "User", "UserName", "Password", "LocalDateTime", "Date", "YearMonth",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
